package com.example.codecup.ui.theme

import androidx.compose.ui.graphics.Color

// Artisan Brew System tokens (see architectural_ui_designer_plan/artisan_brew_system/DESIGN.md)
val CoffeePrimary = Color(0xFF31170B)
val CoffeePrimaryContainer = Color(0xFF4A2C1E)
val CoffeeOnPrimaryContainer = Color(0xFFBE927F)
val CoffeeSecondary = Color(0xFFA53C1B)
val CoffeeSecondaryContainer = Color(0xFFFE7E57)
val CoffeeOnSecondaryContainer = Color(0xFF6F1A00)
val CoffeeAccentContainer = Color(0xFFFBE3DA)
val CoffeeBackground = Color(0xFFFDF9F4)
val CoffeeOnBackground = Color(0xFF1C1C19)
val CoffeeSurface = Color(0xFFFFFFFF)
val CoffeeOnSurface = Color(0xFF1C1C19)
val CoffeeOnSurfaceVariant = Color(0xFF6E5B4E)
val CoffeeOutline = Color(0xFFE4D6C9)
val CoffeeOutlineVariant = Color(0xFFD4C3BC)
val CoffeeSecondaryFixed = Color(0xFFFFDBD1)
val CoffeeTertiaryContainer = Color(0xFF143B0B)
val CoffeeOnTertiaryContainer = Color(0xFF7AA76B)
val CoffeeSurfaceContainerLow = Color(0xFFF7F3EE)
val CoffeeSurfaceContainerHigh = Color(0xFFEBE8E3)
val CoffeeSurfaceContainerLowest = Color(0xFFFFFFFF)
val CoffeeStampGreen = Color(0xFF4F7942)
val CoffeeError = Color(0xFFBA1A1A)
val CoffeeErrorContainer = Color(0xFFFFDAD6)
val CoffeeOnErrorContainer = Color(0xFF93000A)
